### ISSUE TITLE
Added Subscription to the list.

### ISSUE THREAD

**Issue by imomin** [Zertz/stripe-chainable#1]
Can you please add following to the lib? I tested it and it worked fine. If you like you can add filter for status or request all [https://stripe.com/docs/api#list_subscriptions](url)

```
subscription: function (progress, callback) {
    this._chain.push('subscriptions')
    this._options.type = 'subscription'

    if (_.isFunction(progress)) {
      return this.please(progress, callback)
    }

    return this
  }
```

and update supportedObjects

```
    var supportedObjects = ['charge', 'customer', 'plan', 'coupon', 'invoice', 'invoiceItem',
        'transfer', 'applicationFee', 'account', 'event', 'bitcoinReceiver', 'subscription',
        'fileUpload']
```

Thanks!

**Comment by Zertz** [comment]
Thanks! Can you create a PR?

**Comment by imomin** [comment]
Done. Please verify and accept the changes.

**Comment by imomin** [comment]
Please merge the changes, thanks :)

**Comment by imomin** [comment]
Hi @Zertz can you please accept the PR. Thanks!

**Comment by Zertz** [comment]
Merged and published, thanks!
